#!/bin/bash

stamp="/var/lib/update-notifier/updates-available"
[ ! -r "$stamp" ] || cat "$stamp" | head -c -1
find $stamp -newermt 'now-7 days' 2> /dev/null | grep -q -m 1 '.' || /usr/share/update-notifier/notify-updates-outdated
